/**
 * Seed dataset of prominent public and private schools in Kota Gorontalo.
 * Used for initial seeding or testing.
 * Verified coordinates centered around Kota Gorontalo (WITA).
 */

export const KOTA_GORONTALO_SEEDS = [
  {
    name: "SMAN 1 Gorontalo",
    municipality: "Kota Gorontalo",
    district: "Kota Tengah",
    address: "Jl. Jend. Sudirman No. 37, Wumialo",
    lat: 0.5512,
    lng: 123.0583,
    tier: "SMA",
    active: true,
    status: "pending",
  },
  {
    name: "SMAN 2 Gorontalo",
    municipality: "Kota Gorontalo",
    district: "Kota Tengah",
    address: "Jl. Pangeran Hidayat No. 84, Pulubala",
    lat: 0.5594,
    lng: 123.0531,
    tier: "SMA",
    active: true,
    status: "pending",
  },
  {
    name: "SMAN 3 Gorontalo",
    municipality: "Kota Gorontalo",
    district: "Kota Selatan",
    address: "Jl. Panglima Polem No. 47, Limba U Dua",
    lat: 0.5348,
    lng: 123.0617,
    tier: "SMA",
    active: true,
    status: "pending",
  },
  {
    name: "SMAN 4 Gorontalo",
    municipality: "Kota Gorontalo",
    district: "Kota Utara",
    address: "Jl. Brigjend Piola Isa, Dulomo Selatan",
    lat: 0.5701,
    lng: 123.0674,
    tier: "SMA",
    active: true,
    status: "pending",
  },
  {
    name: "SMKN 1 Gorontalo",
    municipality: "Kota Gorontalo",
    district: "Sipatana",
    address: "Jl. Tondano No. 1, Tapa / Sipatana",
    lat: 0.5621,
    lng: 123.0688,
    tier: "SMK",
    active: true,
    status: "pending",
  },
  {
    name: "SMKN 2 Gorontalo",
    municipality: "Kota Gorontalo",
    district: "Kota Tengah",
    address: "Jl. Drs. Achmad Nadjamuddin, Dulalowo Timur",
    lat: 0.5489,
    lng: 123.0652,
    tier: "SMK",
    active: true,
    status: "pending",
  },
  {
    name: "SMKN 3 Gorontalo",
    municipality: "Kota Gorontalo",
    district: "Kota Tengah",
    address: "Jl. Bali No. 1, Pulubala",
    lat: 0.5562,
    lng: 123.056,
    tier: "SMK",
    active: true,
    status: "pending",
  },
  {
    name: "MAN 1 Kota Gorontalo",
    municipality: "Kota Gorontalo",
    district: "Sipatana",
    address: "Jl. Poigar No. 54, Molosipat U",
    lat: 0.5645,
    lng: 123.0634,
    tier: "SMA",
    active: true,
    status: "pending",
  },
  {
    name: "MAN 2 Kota Gorontalo",
    municipality: "Kota Gorontalo",
    district: "Kota Barat",
    address: "Jl. Kasmat Lahay, Tenilo",
    lat: 0.5372,
    lng: 123.0398,
    tier: "SMA",
    active: true,
    status: "pending",
  },
  {
    name: "SMPN 1 Gorontalo",
    municipality: "Kota Gorontalo",
    district: "Kota Timur",
    address: "Jl. Sultan Botutihe No. 17, Ipilo",
    lat: 0.5415,
    lng: 123.0692,
    tier: "SMP",
    active: true,
    status: "pending",
  },
  {
    name: "SMPN 2 Gorontalo",
    municipality: "Kota Gorontalo",
    district: "Kota Timur",
    address: "Jl. HB. Jassin, Moodu",
    lat: 0.5458,
    lng: 123.0781,
    tier: "SMP",
    active: true,
    status: "pending",
  },
  {
    name: "SMPN 6 Gorontalo",
    municipality: "Kota Gorontalo",
    district: "Kota Selatan",
    address: "Jl. Sam Ratulangi No. 4, Limba U Dua",
    lat: 0.5365,
    lng: 123.0601,
    tier: "SMP",
    active: true,
    status: "pending",
  },
  {
    name: "SMA Prasetya Gorontalo",
    municipality: "Kota Gorontalo",
    district: "Sipatana",
    address: "Jl. Ki Hajar Dewantara, Bulotadaa Timur",
    lat: 0.5688,
    lng: 123.072,
    tier: "SMA",
    active: true,
    status: "pending",
  },
  {
    name: "SMA Katolik Santa Maria Gorontalo",
    municipality: "Kota Gorontalo",
    district: "Kota Timur",
    address: "Jl. Nani Wartabone No. 25, Ipilo",
    lat: 0.5392,
    lng: 123.0645,
    tier: "SMA",
    active: true,
    status: "pending",
  },
];
