import { z } from "zod";

export const applicationSchema = z.object({
  displayName: z.string().trim().min(1, "Student name is required."),
  nickname: z.string().trim().optional().default(""),
  phone: z.string().trim().optional().default(""),
  gender: z.string().trim().optional().default(""),
  dob: z.string().trim().optional().default(""),
  placeOfBirth: z.string().trim().optional().default(""),
  religion: z.string().trim().optional().default(""),
  address: z.string().trim().optional().default(""),
  branch: z.string().trim().optional().default(""),
  program: z.string().trim().optional().default(""),
  classType: z.string().trim().optional().default(""),
  schoolOrJob: z.string().trim().optional().default(""),
  classOrSemester: z.string().trim().optional().default(""),
  joinedDate: z.string().trim().optional().default(""),
  fatherName: z.string().trim().optional().default(""),
  fatherJob: z.string().trim().optional().default(""),
  fatherPhone: z.string().trim().optional().default(""),
  motherName: z.string().trim().optional().default(""),
  motherJob: z.string().trim().optional().default(""),
  motherPhone: z.string().trim().optional().default(""),
  parentName: z.string().trim().optional().default(""),
  parentPhone: z.string().trim().optional().default(""),
  photoURL: z.string().trim().optional().default(""),
  referralSource: z.string().trim().optional().default(""),
  currentLevel: z.string().trim().optional().default("warrior"),
  rating: z.string().trim().optional().default("1"),
  paymentPlan: z.string().trim().optional().default("monthly"),
  paidUntil: z.string().trim().optional(),
  status: z.string().trim().optional().default("active"),
  notes: z.string().trim().optional().default(""),
  role: z.literal("student").default("student"),
});
